#!/bin/bash
# Test the Flask app locally using curl with mock GCS Pub/Sub payload.

PORT=${PORT:-8080}
echo "========================================================"
echo "Starting local Flask service..."
echo "========================================================"

# Run the app locally (make sure dependencies are installed)
# Set mock environment variables
export BQ_DATASET="mock_dataset"
export BQ_TABLE="mock_table"
export GCP_PROJECT="mock-project"
export PYTHONPATH="./src:$PYTHONPATH"

# Run Flask app in the background
python src/app.py &
FLASK_PID=$!

# Ensure the background Flask app is terminated on exit
cleanup() {
  echo -e "\nStopping local Flask service (PID: $FLASK_PID)..."
  kill "$FLASK_PID" 2>/dev/null || true
}
trap cleanup EXIT

# Wait for Flask to boot up
sleep 2

echo -e "\nSending health check request..."
curl -s -o /dev/null -w "Health Status: %{http_code}\n" http://localhost:$PORT/healthz

echo -e "\n1. Sending mock Pub/Sub event for sample.txt..."
# Payload attributes simulate the OBJECT_FINALIZE event generated by GCS
# We expect this to fail (500) if no valid GCP credentials are configured locally,
# which verifies our error handling logic!
curl -i -X POST http://localhost:$PORT/ \
  -H "Content-Type: application/json" \
  -d '{
    "message": {
      "attributes": {
        "bucketId": "mock-bucket",
        "objectId": "sample.txt",
        "eventType": "OBJECT_FINALIZE"
      },
      "data": "eyJidWNrZXQiOiAibW9jay1idWNrZXQiLCAibmFtZSI6ICJzYW1wbGUudHh0In0=",
      "messageId": "11111111"
    }
  }'

echo -e "\n\n2. Sending mock Pub/Sub event for test_image.png..."
curl -i -X POST http://localhost:$PORT/ \
  -H "Content-Type: application/json" \
  -d '{
    "message": {
      "attributes": {
        "bucketId": "mock-bucket",
        "objectId": "test_image.png",
        "eventType": "OBJECT_FINALIZE"
      },
      "data": "eyJidWNrZXQiOiAibW9jay1idWNrZXQiLCAibmFtZSI6ICJ0ZXN0X2ltYWdlLnBuZyJ9",
      "messageId": "22222222"
    }
  }'

echo -e "\n\n3. Sending non-creation event (should be skipped with 200)..."
curl -i -X POST http://localhost:$PORT/ \
  -H "Content-Type: application/json" \
  -d '{
    "message": {
      "attributes": {
        "bucketId": "mock-bucket",
        "objectId": "sample.txt",
        "eventType": "OBJECT_DELETE"
      },
      "data": "eyJidWNrZXQiOiAibW9jay1idWNrZXQiLCAibmFtZSI6ICJzYW1wbGUudHh0In0=",
      "messageId": "33333333"
    }
  }'

echo -e "\nLocal verification complete."
